export const data = [
  {
    id: 1,
    plan: "Basic",
    price: 9,
    period: "month",
    description: "Perfect for individuals ad small projects",
    icon: "fas fa-rocket",
    isPopular: false,
    perks: [
      { name: "5 Projects", isEnabled: true },
      { name: "20Gb Storage", isEnabled: true },
      { name: "Basic Support", isEnabled: true },
      { name: " Email Notification", isEnabled: true },
      { name: " Advanced Analytics", isEnabled: false },
      { name: "Custom Support", isEnabled: false },
    ],
  },
  {
    id: 2,
    plan: "Pro",
    price: 29,
    period: "month",
    description: "Great for growing business and teams",
    icon: "fas fa-gem",
    isPopular: true,
    perks: [
      { name: "5 Projects", isEnabled: true },
      { name: "20Gb Storage", isEnabled: true },
      { name: "Basic Support", isEnabled: true },
      { name: " Email Notification", isEnabled: true },
      { name: " Advanced Analytics", isEnabled: true },
      { name: "Custom Support", isEnabled: false },
    ],
  },
  {
    id: 3,
    plan: "Enterprise",
    price: 79,
    period: "month",
    description: "For large companies and organizations",
    icon: "fas fa-building",
    isPopular: false,
    perks: [
      { name: "5 Projects", isEnabled: true },
      { name: "20Gb Storage", isEnabled: true },
      { name: "Basic Support", isEnabled: true },
      { name: " Email Notification", isEnabled: true },
      { name: " Advanced Analytics", isEnabled: true },
      { name: "Custom Support", isEnabled: true },
    ],
  },
];
